# Site settings
author: Andrew Bourgeois
title: Ironed Flat
header-img: img/home-bg.png
email: andrew@olympicmedia.com
copyright_name: Andrew Bourgeois
description: > # this means to ignore newlines until "baseurl:"
  A coding journey through Flatiron's Software Development Bootcamp
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  asb1512

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
